sudo: required
dist: trusty
language: ruby
before_install:
  - gem update --system --no-doc
  - bin/provision.sh
rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - ruby-head
env:
  - TEST_TASK=spec

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: jruby-9.1.17.0
    - rvm: jruby-9.2.5.0
    - rvm: "2.6"
      env: influx_version=nightly channel=nightlies
  include:
    - rvm: "2.6"
      env: TEST_TASK=rubocop

    - rvm: jruby-9.1.17.0
      env: JRUBY_OPTS='--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Xss2m -J-Xmx256M'
    - rvm: jruby-9.2.5.0
      env: JRUBY_OPTS='--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Xss2m -J-Xmx256M'
    - rvm: jruby-head
      env: JRUBY_OPTS='--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Xss2m -J-Xmx256M'

    - rvm: "2.6"
      env: influx_version=1.0.2 pkghash=88f6c30fec2c6e612e802e23b9161fdfc7c5c29f6be036f0376326445aff0037
    - rvm: "2.6"
      env: influx_version=1.1.5 pkghash=0ecb9385cc008f6e5094e6e8f8ea70522023a16d4397e401898f3973176d3b21
    - rvm: "2.6"
      env: influx_version=1.2.4 pkghash=2fac8391e04aa1bec9151e8f0d8f18df030c866af2b4963ab7d86c6ddc172182
    - rvm: "2.6"
      env: influx_version=1.3.8 pkghash=35c9cb2943bbde04aa5e94ad6d8caf5fc9b1480bdbcde7c34078de135cc4f788
    - rvm: "2.6"
      env: influx_version=1.4.3 pkghash=0477080f1d1cf8e1242dc7318280b9010c4c45cf6a415a2a5de607ae17fa0359
    - rvm: "2.6"
      env: influx_version=1.5.4 pkghash=fa6f8d3196d13ffc376d533581b534692c738181ce3427c53484c138d9e6b902
    - rvm: "2.6"
      env: influx_version=1.6.4 pkghash=dbfa13a0f9e38a8e7b19294c30144903bb681ac0aba0a3a8f4f349c37d5de5f9
    - rvm: "2.6"
      env: influx_version=1.7.2 pkghash=0bce61b7d89bf3216a7d3cb7a38423bd1c3a1b7d2ea8086b39cb26130ad78995
    - rvm: "2.6"
      env: influx_version=nightly channel=nightlies
addons:
  apt:
    packages:
      - haveged
      - libgmp-dev
script: travis_retry bundle exec rake $TEST_TASK
